# サービス名（必須）
service: bright_talk

# Name of the container image
image: darwin2008/bright_talk

# Deploy to these servers
servers:
  web:
    - 18.206.143.227

# Enable SSL auto certification via Let's Encrypt
proxy:
  ssl: true
  host: www.brighttalk.jp

# Credentials for your image host
registry:
  username: darwin2008
  password:
    - KAMAL_REGISTRY_PASSWORD

# Configure the image builder
builder:
  arch: amd64
  local: true

# Inject ENV variables into containers
env:
  secret:
    - RAILS_MASTER_KEY
  clear:
    SOLID_QUEUE_IN_PUMA: true
    RAILS_ENV: production
    RAILS_LOG_LEVEL: info
    RAILS_SERVE_STATIC_FILES: true
    RAILS_LOG_TO_STDOUT: true

# SSH configuration
ssh:
  user: ubuntu
  keys_only: true
  keys:
    - ssh-keys/brighttalk-production-key.pem

# Aliases for common commands
aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"

# Use a persistent storage volume
volumes:
  - "bright_talk_storage:/rails/storage"
  - "bright_talk_db:/rails/db"

# Bridge fingerprinted assets
asset_path: /rails/public/assets