# サービス名（必須）
service: bright_talk

# Name of the container image
image: darwin2008/bright_talk

# Deploy to these servers
servers:
  web:
    - 35.75.129.232

# Enable SSL auto certification via Let's Encrypt
proxy:
  ssl: true
  host: www.brighttalk.jp

# Credentials for your image host
registry:
  username: darwin2008
  password:
    - DOCKER_HUB_PASSWORD

# Inject ENV variables into containers
env:
  secret:
    - RAILS_MASTER_KEY
  clear:
    SOLID_QUEUE_IN_PUMA: "true"
    RAILS_ENV: "production"
    RAILS_LOG_LEVEL: "info"
    RAILS_SERVE_STATIC_FILES: "true"
    RAILS_LOG_TO_STDOUT: "true"

# SSH configuration
ssh:
  user: ec2-user
  keys_only: true
  keys:
    - ssh-keys/brighttalk-production-key.pem

# Aliases for common commands
aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"

# Use a persistent storage volume
volumes:
  - "bright_talk_storage:/rails/storage"
  - "bright_talk_db:/rails/db"

# Bridge fingerprinted assets
asset_path: /rails/public/assets

# Configure the image builder (remoteを削除またはコメントアウト)
builder:
  arch: amd64
  cache:
    type: registry
    options: mode=max
  # remote: true  # この行が問題の原因