
service: brighttalk

image: brighttalk-app

servers:
  web:
    hosts:
      - 54.150.47.143.
    labels:
      traefik.enable: true
      traefik.http.routers.web.entrypoints: websecure
      traefik.http.routers.web.rule: Host(`brighttalk.jp`) || Host(`www.brighttalk.jp`)
      traefik.http.routers.web.tls.certresolver: letsencrypt
      traefik.http.routers.web.middlewares: redirect-to-https

registry:
  server: 891377308994.dkr.ecr.us-east-1.amazonaws.com
  username: AWS
  password:
    - aws ecr get-login-password --region us-east-1

env:
  clear:
    PORT: 3000
  secret:
    - RAILS_MASTER_KEY

traefik:
  options:
    publish:
      - "80:80"
      - "443:443"
    volume:
      - "/letsencrypt/acme.json:/acme.json"
  args:
    entrypoints.web.address: ":80"
    entrypoints.websecure.address: ":443"

    # HTTPからHTTPSへのリダイレクト
    entrypoints.web.http.redirections.entrypoint.to: websecure
    entrypoints.web.http.redirections.entrypoint.scheme: https

    # Let's Encrypt設定
    certificatesresolvers.letsencrypt.acme.email: admin@brighttalk.jp
    certificatesresolvers.letsencrypt.acme.storage: /acme.json
    certificatesresolvers.letsencrypt.acme.httpchallenge: true
    certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint: web

# 任意：アクセサリ（今回は不要）
# accessories:
#   db:
#     image: postgres:15
  #     host: 18.206.143.227