# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.4
          bundler-cache: true

      - name: Setup Database
        env:
          RAILS_ENV: test
        run: |
          bin/rails db:create
          bin/rails db:migrate
          bin/rails db:fixtures:load

      - name: Run tests (sequential execution for CI stability)
        env:
          RAILS_ENV: test
          # 並列実行を無効化
          PARALLEL_WORKERS: 1
        run: |
          # フィクスチャを再読み込み
          bin/rails db:fixtures:load
          # シーケンシャル実行でテストを実行
          bin/rails test --verbose
          bin/rails test:system --verbose

      - name: Run RuboCop
        run: bundle exec rubocop