# .github/workflows/ci.yml
name: CI

on:
  workflow_dispatch:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.4
          bundler-cache: true

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Node.js dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Setup Database
        env:
          RAILS_ENV: test
          CI: true
        run: |
          sudo apt-get update
          sudo apt-get install -y libvips
          bin/rails db:create
          bin/rails db:migrate
          bin/rails db:fixtures:load

      - name: Run JavaScript tests
        run: npm test

      - name: Run Rails tests (sequential execution for CI)
        env:
          RAILS_ENV: test
          CI: true
          PARALLEL_WORKERS: 1
        run: |
          bin/rails test --verbose
          bin/rails test:system --verbose

      - name: Run RuboCop
        run: bundle exec rubocop
