
# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.4
          bundler-cache: true

      - name: Setup Database
        env:
          RAILS_ENV: test
          CI: true
        run: |
          bin/rails db:create
          bin/rails db:migrate
          bin/rails db:fixtures:load

      - name: Run tests (sequential execution for CI)
        env:
          RAILS_ENV: test
          CI: true
        run: |
          bin/rails test --verbose
          bin/rails test:system --verbose

      - name: Run RuboCop
        run: bundle exec rubocop